# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# Minecraft / Forge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
forge_version=52.1.14
forge_version_range=[52,)
loader_version_range=[52,)
mapping_channel=official
mapping_version=1.21.1
# Mod
mod_id=sylvaria
mod_name=Sylvaria
mod_license=MIT
mod_version=1.0.0
mod_group_id=net.sylvariamod
mod_authors=YourName
mod_description=A magical forest dimension mod, reachable through an ancient portal.
